import { GROCERY } from ".";
export const products = [
  {
    id: 1,
    image:
      "https://png.pngtree.com/png-clipart/20250221/original/pngtree-full-shopping-cart-with-groceries-and-bags-on-transparent-background-png-image_20490606.png",
    description: "Classic White Sneakers",
    currentPrice: 49.99,
    oldPrice: 79.99,
    discount: 38,
  },
  {
    id: 2,
    image: GROCERY,
    description: "Leather Travel Backpack",
    currentPrice: 69.99,
    oldPrice: 99.99,
    discount: 30,
  },
  {
    id: 3,
    image: GROCERY,
    description: "Men’s Analog Watch",
    currentPrice: 129.99,
    oldPrice: 189.99,
    discount: 32,
  },
  {
    id: 4,
    image: "https://via.placeholder.com/300?text=Headphones",
    description: "Wireless Noise-Cancelling Headphones",
    currentPrice: 89.99,
    oldPrice: 149.99,
    discount: 40,
  },
  {
    id: 5,
    image: "https://via.placeholder.com/300?text=T-Shirt",
    description: "Cotton Crew Neck T-Shirt",
    currentPrice: 15.99,
    oldPrice: 24.99,
    discount: 36,
  },
  {
    id: 6,
    image: "https://via.placeholder.com/300?text=Jacket",
    description: "Windbreaker Sports Jacket",
    currentPrice: 59.99,
    oldPrice: 89.99,
    discount: 33,
  },
  {
    id: 7,
    image: "https://via.placeholder.com/300?text=Smartphone",
    description: "Smartphone with AMOLED Display",
    currentPrice: 399.99,
    oldPrice: 499.99,
    discount: 20,
  },
  {
    id: 8,
    image: "https://via.placeholder.com/300?text=Laptop",
    description: "Ultra-Slim Business Laptop",
    currentPrice: 899.99,
    oldPrice: 1199.99,
    discount: 25,
  },
  {
    id: 9,
    image: "https://via.placeholder.com/300?text=Sunglasses",
    description: "Polarized Aviator Sunglasses",
    currentPrice: 34.99,
    oldPrice: 59.99,
    discount: 42,
  },
  {
    id: 10,
    image: "https://via.placeholder.com/300?text=Perfume",
    description: "Luxury Eau De Parfum - 100ml",
    currentPrice: 54.99,
    oldPrice: 89.99,
    discount: 39,
  },
  {
    id: 11,
    image: "https://via.placeholder.com/300?text=Jeans",
    description: "Slim Fit Denim Jeans",
    currentPrice: 44.99,
    oldPrice: 69.99,
    discount: 36,
  },
  {
    id: 12,
    image: "https://via.placeholder.com/300?text=Boots",
    description: "Waterproof Hiking Boots",
    currentPrice: 99.99,
    oldPrice: 139.99,
    discount: 29,
  },
  {
    id: 13,
    image: "https://via.placeholder.com/300?text=Keyboard",
    description: "Mechanical RGB Gaming Keyboard",
    currentPrice: 59.99,
    oldPrice: 89.99,
    discount: 33,
  },
  {
    id: 14,
    image: "https://via.placeholder.com/300?text=Monitor",
    description: "27-inch 4K UHD Monitor",
    currentPrice: 299.99,
    oldPrice: 399.99,
    discount: 25,
  },
  {
    id: 15,
    image: "https://via.placeholder.com/300?text=Mouse",
    description: "Ergonomic Wireless Mouse",
    currentPrice: 24.99,
    oldPrice: 39.99,
    discount: 38,
  },
  {
    id: 16,
    image: "https://via.placeholder.com/300?text=Desk+Lamp",
    description: "LED Adjustable Desk Lamp",
    currentPrice: 29.99,
    oldPrice: 49.99,
    discount: 40,
  },
  {
    id: 17,
    image: "https://via.placeholder.com/300?text=Chair",
    description: "Ergonomic Office Chair",
    currentPrice: 149.99,
    oldPrice: 199.99,
    discount: 25,
  },
  {
    id: 18,
    image: "https://via.placeholder.com/300?text=Speaker",
    description: "Bluetooth Portable Speaker",
    currentPrice: 39.99,
    oldPrice: 59.99,
    discount: 33,
  },
  {
    id: 19,
    image: "https://via.placeholder.com/300?text=Blender",
    description: "High-Speed Kitchen Blender",
    currentPrice: 74.99,
    oldPrice: 109.99,
    discount: 32,
  },
  {
    id: 20,
    image: "https://via.placeholder.com/300?text=Watch+2",
    description: "Luxury Stainless Steel Watch",
    currentPrice: 199.99,
    oldPrice: 299.99,
    discount: 33,
  },
];
